layout = { 'one': 'left',
			'two': 'up',
			'three': 'right',
			'four': 'copy',
			'five': 'paste',
			'six': 'overdub',
			'seven': 'tap_tempo',
			'eight': 'undo',
			
			'nine': 'enter',
			'ten': 'down',
			'eleven': 'prev_pre_pat',
			'twelve': 'next_pre_pat',
			'thirteen': 'loop_record',
			'fourteen': 'stop',
			'fifteen': 'start',
			'sixteen': 'record',

			'seventeen': 'left', 
			'eighteen': 'up', 
			'nineteen': 'right', 
			'twenty': 'copy', 
			'twentyone': 'paste', 
			'twentytwo': 'rand_pat', 
			'twentythree': 'metronome', 
			'twentyfour': 'undo_up', 

			'twentyfive': 'enter', 
			'twentysix': 'down', 
			'twentyseven': 'prev_pre_pat', 
			'twentyeight': 'next_pre_pat', 
			'twentynine': 'loop_record', 
			'thirty': 'stop', 
			'thirtyone': 'start', 
			'thirtytwo': 'record', 				
}
