layout = { 'one': 'left',
			'two': 'up',
			'three': 'right',
			'four': 'copy',
			'five': 'paste',
			'six': 'overdub',
			'seven': 'tap_tempo',
			'eight': 'undo',

			'nine': 'enter',
			'ten': 'down',
			'eleven': 'prev_pre_pat',
			'twelve': 'next_pre_pat',
			'thirteen': 'loop_record',
			'fourteen': 'stop',
			'fifteen': 'start',
			'sixteen': 'record',

			'seventeen': 'left', 
			'eighteen': 'up', 
			'nineteen': 'right', 
			'twenty': 'copy', 
			'twentyone': 'paste', 
			'twentytwo': 'rand_pat', 
			'twentythree': 'metronome', 
			'twentyfour': 'undo_up', 

			'twentyfive': 'enter', 
			'twentysix': 'down', 
			'twentyseven': 'prev_pre_pat', 
			'twentyeight': 'next_pre_pat', 
			'twentynine': 'loop_record', 
			'thirty': 'stop', 
			'thirtyone': 'start', 
			'thirtytwo': 'start',

			"thirtythree": 'item_menu',
			"thirtyfour": 'change_color',
			"thirtyfive": 'trig_clip',
			"thirtysix": 'solo',
			"thirtyseven": 'snap_toggle',
			"thirtyeight": 'menu',
			"thirtynine": 'save',
			"forty": '',

			"fortyone": 'quantize',
			"fortytwo": 'arm_track',
			"fortythree": 'focus_browser',
			"fortyfour": 'enter',
			"fortyfive": 'up',
			"fortysix": 'down',
			"fortyseven": 'countdown',
			"fortyeight": 'rand_notes',

			"knob_one": 'channel_mixer',
			"knob_two": 'open_channel',
			"knob_three": 'mute', 	
			"knob_four": 'solo',
			"knob_five": 'rand_pat',			
			}

layout_b = { 'one_b': 'left',
			'two_b': 'up',
			'three_b': 'right',
			'four_b': 'escape',
			'five_b': 'paste',
			'six_b': 'overdub',
			'seven_b': 'rand_notes',
			'eight_b': 'focus_browser',

			'nine_b': 'enter',
			'ten_b': 'down',
			'eleven_b': 'prev_pre_pat',
			'twelve_b': 'next_pre_pat',
			'thirteen_b': 'loop_record',
			'fourteen_b': 'stop',
			'fifteen_b': 'start',
			'sixteen_b': 'record'
			}